### PR TITLE
Dropped dependency on ramda

### PR DESCRIPTION
**Pull request by amireh**
A quick implementation for #1.

### CODE REVIEW

**Comment by philcockfield** [comment]
Looks good.

Out of interest are you using this for non-UI related schema checking?  
It's an incredibly elegant and concise schema system they've created, I'm finding myself using it to validate data on the server that is eventually going to make it's way to the UI layer.

What's your general use-case @amireh

**Comment by amireh** [comment]
Thanks. I have a few scenarios I need it in, one of them is a bit crazy.

The first is that we try to adopt a white-list based approach to all of our outbound and inbound XHRs; you only send what you explicitly specify (through a schema) and you may use only what you expect (through another schema.) We need to introspect the schema for this reason; to be able to white-list parameters.

So far I've been using an incomplete home-grown solution to make that possible. This approach has led to developer happiness because anyone can easily tell what each ajax request will contain without having to go through console debugging and such, it just makes the code more readable (never-mind the integrity boost!)

The other use-case is a bit more interesting. Since we know what our client expects from the API (through the aforementioned schemas,) we also have a way of analyzing what our API emits (I can't speak much of the server technology since it's closed-source.) Through this, we calculate a "conformity index" that lets us know if/when this contract gets broken by either end (i.e. if the API has stopped emitting a payload item that the client is relying on, or if the client is relying on something the API does not emit, perhaps a mis-typed key.)

---

I see we still need some more work here for `arrayOf` support and some other things. I will look into other PRs soon. Thank you.

**Comment by amireh** [comment]
BTW, static (and now run-time, thx to ur library) analysis of PropTypes has allowed me to do things like real-time preview of components as u can see here http://tinydoc.github.io/tinydoc-plugin-react/#/demo/modules/Checkbox (click on the `Try it!` link to see what I mean)

**Comment by philcockfield** [comment]
Super interesting context - thanks @amireh!

Runtime analysis of `PropTypes`....FTW! :+1:

**Pull request merged**
